version: "1.0"

# http://localhost:8081/  - adminer
# http://localhost:8025/  - mailhog

services:

  mysql:
    image: mariadb:latest
    restart: always
    command: mysqld --sql_mode=""
    env_file:
      - env/mysql.env
    ports:
      - "3306:3306"

  backend:
    image: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:43"
    depends_on:
      - mysql
    volumes:
      - ./src:/usr/share/nginx/html/project

  adminer:
    image: adminer:4.6.2
    restart: always
    ports:
      - "8081:8080"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - "11211:11211"

  mailhog:
    image: teawithfruit/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
